"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trainerService } from "@/services/trainer/trainer.service";
import type { ApiRecord } from "@/types/administration";

function Shell({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="mx-auto max-w-4xl space-y-6"><div><h1 className="font-display text-3xl font-bold text-primary">{title}</h1><p className="mt-1 text-sm text-grey-60">{description}</p></div><Card className="p-6">{children}</Card></div>; }
function FormActions({ busy }: { busy: boolean }) { const router=useRouter(); return <div className="mt-5 flex gap-2"><Button type="submit" disabled={busy}>{busy?"Saving…":"Save"}</Button><Button type="button" variant="outline" onClick={()=>router.back()}>Cancel</Button></div>; }

export function TrainerCourseCreateView(){const router=useRouter();const [busy,setBusy]=useState(false);const [f,setF]=useState({title:"",category:"",level:"Beginner to Advanced",description:""});return <Shell title="Create course" description="Build a trainer-owned course in draft status, then submit it for admin approval."><form onSubmit={async e=>{e.preventDefault();if(!f.title.trim())return toast.error("Title is required");setBusy(true);try{await trainerService.createCourse(f);toast.success("Course created in draft");router.push("/trainer/courses");router.refresh()}catch(err){toast.error(err instanceof Error?err.message:"Create failed")}finally{setBusy(false)}}}><div className="grid gap-4 md:grid-cols-2"><Input placeholder="Course title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><Input placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/><Input placeholder="Level" value={f.level} onChange={e=>setF({...f,level:e.target.value})}/><textarea className="min-h-32 rounded-lg border border-grey-20 p-3 text-sm md:col-span-2" placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></div><FormActions busy={busy}/></form></Shell>}

export function TrainerBatchCreateView(){const router=useRouter();const [busy,setBusy]=useState(false);const [courses,setCourses]=useState<ApiRecord[]>([]);const [f,setF]=useState({name:"",courseId:"",startDate:"",endDate:"",description:"",status:"active"});useEffect(()=>{trainerService.listCourses().then(r=>setCourses(r.items as unknown as ApiRecord[])).catch(e=>toast.error(e instanceof Error?e.message:"Unable to load courses"))},[]);return <Shell title="Create batch" description="Assign a cohort to one of your courses and define its delivery period."><form onSubmit={async e=>{e.preventDefault();if(!f.name.trim()||!f.courseId)return toast.error("Batch name and course are required");setBusy(true);try{await trainerService.createBatch(f);toast.success("Batch created");router.push("/trainer/batches");router.refresh()}catch(err){toast.error(err instanceof Error?err.message:"Create failed")}finally{setBusy(false)}}}><div className="grid gap-4 md:grid-cols-2"><Input placeholder="Batch name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select className="rounded-lg border border-grey-20 px-3 py-2.5 text-sm" value={f.courseId} onChange={e=>setF({...f,courseId:e.target.value})}><option value="">Select course</option>{courses.map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.title)}</option>)}</select><Input type="date" value={f.startDate} onChange={e=>setF({...f,startDate:e.target.value})}/><Input type="date" value={f.endDate} onChange={e=>setF({...f,endDate:e.target.value})}/><textarea className="min-h-28 rounded-lg border border-grey-20 p-3 text-sm md:col-span-2" placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></div><FormActions busy={busy}/></form></Shell>}

export function TrainerAssessmentCreateView(){const router=useRouter();const [busy,setBusy]=useState(false);const [batches,setBatches]=useState<ApiRecord[]>([]);const [f,setF]=useState({title:"",type:"Quiz",batchId:"",dueAt:"",durationMinutes:"30",questionCount:"10",description:""});useEffect(()=>{trainerService.listBatches().then(r=>setBatches(r.items as unknown as ApiRecord[])).catch(e=>toast.error(e instanceof Error?e.message:"Unable to load batches"))},[]);return <Shell title="Create assessment" description="Schedule an assessment for a trainer-managed batch."><form onSubmit={async e=>{e.preventDefault();if(!f.title.trim())return toast.error("Assessment title is required");setBusy(true);try{await trainerService.createAssessment({...f,dueAt:f.dueAt?new Date(f.dueAt).toISOString():undefined,durationMinutes:Number(f.durationMinutes),questionCount:Number(f.questionCount)});toast.success("Assessment created in draft");router.push("/trainer/assessments");router.refresh()}catch(err){toast.error(err instanceof Error?err.message:"Create failed")}finally{setBusy(false)}}}><div className="grid gap-4 md:grid-cols-2"><Input placeholder="Title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><select className="rounded-lg border border-grey-20 px-3 py-2.5 text-sm" value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>Quiz</option><option>Assignment</option><option>Viva</option><option>Project</option></select><select className="rounded-lg border border-grey-20 px-3 py-2.5 text-sm" value={f.batchId} onChange={e=>setF({...f,batchId:e.target.value})}><option value="">Select batch</option>{batches.map(b=><option key={String(b.id)} value={String(b.id)}>{String(b.name)}</option>)}</select><Input type="datetime-local" value={f.dueAt} onChange={e=>setF({...f,dueAt:e.target.value})}/><Input type="number" min="5" value={f.durationMinutes} onChange={e=>setF({...f,durationMinutes:e.target.value})}/><Input type="number" min="1" value={f.questionCount} onChange={e=>setF({...f,questionCount:e.target.value})}/><textarea className="min-h-28 rounded-lg border border-grey-20 p-3 text-sm md:col-span-2" placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></div><FormActions busy={busy}/></form></Shell>}

export function TrainerLiveClassCreateView(){const router=useRouter();const [busy,setBusy]=useState(false);const [batches,setBatches]=useState<ApiRecord[]>([]);const [f,setF]=useState({title:"",batchId:"",startsAt:"",durationMinutes:"60",roomUrl:""});useEffect(()=>{trainerService.listBatches().then(r=>setBatches(r.items as unknown as ApiRecord[])).catch(e=>toast.error(e instanceof Error?e.message:"Unable to load batches"))},[]);return <Shell title="Create live class" description="Schedule a live trainer session for a batch."><form onSubmit={async e=>{e.preventDefault();if(!f.title.trim()||!f.batchId||!f.startsAt)return toast.error("Title, batch and start time are required");setBusy(true);try{await trainerService.createSession({...f,startsAt:f.startsAt?new Date(f.startsAt).toISOString():undefined,durationMinutes:Number(f.durationMinutes)});toast.success("Live class scheduled");router.push("/trainer/live-classes");router.refresh()}catch(err){toast.error(err instanceof Error?err.message:"Create failed")}finally{setBusy(false)}}}><div className="grid gap-4 md:grid-cols-2"><Input placeholder="Class title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><select className="rounded-lg border border-grey-20 px-3 py-2.5 text-sm" value={f.batchId} onChange={e=>setF({...f,batchId:e.target.value})}><option value="">Select batch</option>{batches.map(b=><option key={String(b.id)} value={String(b.id)}>{String(b.name)}</option>)}</select><Input type="datetime-local" value={f.startsAt} onChange={e=>setF({...f,startsAt:e.target.value})}/><Input type="number" min="15" value={f.durationMinutes} onChange={e=>setF({...f,durationMinutes:e.target.value})}/><Input className="md:col-span-2" placeholder="Meeting room URL" value={f.roomUrl} onChange={e=>setF({...f,roomUrl:e.target.value})}/></div><FormActions busy={busy}/></form></Shell>}
